name: Testing develop

on:
  pull_request:
    branches: ["develop"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - run: npm ci --only=dev  
    - run: npm run lint
