name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: secret
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
      new-release-git-tag: ${{ steps.get-next-version.outputs.new-release-git-tag }}
  
  deploy:
    runs-on: ubuntu-latest
    environment: secret
    needs: release
    if: needs.release.outputs.new-release-published == 'true'
    env:
      PORT: 4000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Validate build configuration
        uses: docker/build-push-action@v7
        with:
          call: check
      
      - run: echo "The new release version is ${{ needs.release.outputs.new-release-version }}"
      - run: echo "The new release git tag is ${{ needs.release.outputs.new-release-git-tag }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          # list of Docker images to use as base name for tags
          images: |
            nhcuong/cau-long-bot
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            nhcuong/cau-long-bot:${{ needs.release.outputs.new-release-version }}
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            nhcuong/cau-long-bot:${{ needs.release.outputs.new-release-version }}

      - name: Copy docker compose
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_VIETNIX }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "compose.prod.yaml"
          target: "/app/cau-long-bot"
        
      - name: Deploy to VPS via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        env:
          # Lấy chính xác version mà bước 'meta' đã xác định
          DEPLOY_TAG: ${{ steps.meta.outputs.version }}
          PORT: ${{ env.PORT }}
        with:
          host: ${{ secrets.SSH_HOST_VIETNIX }}
          username: ${{ secrets.SSH_USER }}
          envs: DEPLOY_TAG, PORT
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export TAG=$DEPLOY_TAG
            export PORT=$PORT

            echo "Deploying version $TAG"
            echo "Deploying to port $PORT"
          
            cd /app/cau-long-bot
            
            # change name
            mv compose.prod.yaml compose.yaml

            # create env
            mkdir -p db
            echo "
              BOT_TOKEN=${{ secrets.BOT_TOKEN }}
              ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}
            " >> .env

            docker compose pull
            docker compose up -d --name cau-long-bot
            docker image prune -af  # Xóa image cũ để tiết kiệm ổ cứng VPS

            sleep 10
            curl -f http://localhost:${PORT}/restart-cron || exit 1